### ISSUE TITLE
Item prices ids aren't sent well

### ISSUE THREAD

**Issue by sfroment** [chargebee/chargebee-go#22]
Hello, 
if you try to make a `UpdateForItemsRequestParams` request with some item_price_ids it will then fail with the following
```
item_constraints[item_price_ids] : item_price_ids should be sent when constraint is passed as specific","param":"item_constraints[item_price_ids
```

Here what the params sent look like: 

```
item_price_ids[cbdemo_intermediary-USD-yearly][0]:[cbdemo_intermediary-USD-yearly]
```

if you were adding 

```go
itemPriceIds := []map[string]interface{}{
	  {
	  "cbdemo_intermediary-USD-yearly": "cbdemo_intermediary-USD-yearly",
	  },
}
```

There are multiple problem on fixing this first getParamTypes won't return a map containing the name of any "inner" type so `item_price_ids` won't be int the ending up paramTypes map that is used to generate the params

same problem as here https://github.com/chargebee/chargebee-ruby/issues/64

**Comment by derekperkins** [comment]
We have the same issue. cc @mordfustang21

**Comment by derekperkins** [comment]
@cb-khushbubibay @cb-yateshmathuria @cb-prajaktachavan There's an open PR to fix this. Is anyone paying attention to this repo?

**Comment by derekperkins** [comment]
Where we're trying to set constraints on coupons, the field is just `json.RawMessage`, which isn't useful
https://github.com/chargebee/chargebee-go/blob/master/models/coupon/coupon.go#L47

**Comment by cb-khushbubibay** [comment]
Hi @derekperkins 
This issue has been fixed in v2.13.2. Request you to please upgrade to latest version.

**Comment by derekperkins** [comment]
That's definitely not fixed. The field is an array of item price ids, and you just turned it into a string

**Comment by cb-aram** [comment]
@derekperkins with this fix you could pass a stringfied json array as the value. 
Example: 
      itemPriceIds := "[\"cbdemo_intermediary-USD-yearly\"]"

**Comment by cb-khushbubibay** [comment]
@derekperkins We have fixed this issue, now you have to pass array as below:
**1- For the field which does not contain map structure**
 _ItemPriceIds: []interface{}{"cbdemo_basic-USD-monthly, dcd-USD-Daily"}_
**2- For the field which contains map structure**
 _ExemptionDetails: []map[string]interface{}{
        { "loc" : map[string]interface{}{
             "addr" : "sdfsd,dsf",
             "st" : "TX",
             "ctry" : "USA",
             "zip" : "87799",
         },
         "cat" : 0,
         "exnb" : true,
         "frc" : true,
         "scp" : 1920,
        },
       { "loc" : map[string]interface{}{
           "addr" : "sdfsd,dsf",
           "st" : "TX",
           "ctry" : "USA",
           "zip" : "87799",
       },
           "cat" : 0,
           "exnb" : true,
           "frc" : true,
           "scp" : 1920,
       },
      },_
